meta:
  device: cuda

training:
  dataset: cifar10
  weight: null
  epochs: 2
  model: mlp_layer7
  loss: cross_entropy_loss
  optimizer: adam
  lr_scheduler: null
  early_stopping: false

# 検証の設定
evaluation:
  metrics: [accuracy, f1]
  save_best_monitor: accuracy
  monitor_task: max